web/router.ex
defmodule Librarian.Router do
  use Librarian.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Librarian do
    pipe_through :browser # Use the default browser stack

    get "/", BookController, :index
    resources "/genres", GenreController
    resources "/books",  BookController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Librarian do
  #   pipe_through :api
  # end
end

lib/librarian/endpoint.ex
defmodule Librarian.Endpoint do
  use Phoenix.Endpoint, otp_app: :librarian

  socket "/socket", Librarian.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :librarian, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_librarian_key",
    signing_salt: "010p+t6I"

  plug Librarian.Router
end

lib/librarian/repo.ex
defmodule Librarian.Repo do
  use Ecto.Repo, otp_app: :librarian
end

web/models/book.ex
defmodule Librarian.Book do
  use Librarian.Web, :model

  schema "books" do
    field :title, :string
    field :isbn, :string
    field :store_loc, :string

    belongs_to :genre, Librarian.Genre, foreign_key: :genre_id
    
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :isbn, :store_loc, :genre_id])
    |> validate_required([:title, :isbn, :store_loc, :genre_id])
    |> unique_constraint(:isbn)
  end
end

web/models/genre.ex
defmodule Librarian.Genre do
  use Librarian.Web, :model

  schema "genres" do
    field :name, :string

    has_many :books, Librarian.Book, on_delete: :delete_all
    
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

web/controllers/book_controller.ex
defmodule Librarian.BookController do
  use Librarian.Web, :controller

  def index(conn, _params) do
    books = Repo.all(Librarian.Book)
    render conn, "index.html", books: books
  end

  def show(conn, _params) do
    book  = Repo.preload(Repo.get(Librarian.Book, _params["id"]), :genre)
    render conn, "show.html", book: book
  end

  def new(conn, _params) do
    book  = Librarian.Book.changeset(%Librarian.Book{}, %{})
    genre = Enum.map(Repo.all(Librarian.Genre), &{&1.name, &1.id})
    render conn, "new.html", book: book, genre: genre
  end

  def create(conn, _params) do
    book = Librarian.Book.changeset(%Librarian.Book{}, _params["book"])
    case Repo.insert(book)  do
      {:ok, book} ->
        redirect conn, to: "/books"
      {:error, book} ->
        genre = Enum.map(Repo.all(Librarian.Genre), &{&1.name, &1.id})
        render(conn, "new.html", book: book, genre: genre)
    end
  end

  def edit(conn, _params) do
    book = Repo.get(Librarian.Book, _params["id"])
    genre = Enum.map(Repo.all(Librarian.Genre), &{&1.name, &1.id})
    changeset = Librarian.Book.changeset(book)
    render conn, "edit.html", book: book, genre: genre, changeset: changeset
  end

  def update(conn, _params) do
    book = Repo.get(Librarian.Book, _params["id"])
    changeset = Librarian.Book.changeset(book, _params["book"])
    case Repo.update(changeset) do
      {:ok, book} ->
        redirect conn, to: "/books"
      {:error, changeset} ->
        genre = Enum.map(Repo.all(Librarian.Genre), &{&1.name, &1.id})
        render(conn, "edit.html", book: book, changeset: changeset, genre: genre)
    end      
  end


  def delete(conn, _params) do
    book = Repo.get(Librarian.Book, _params["id"])
    Repo.delete(book)
    redirect conn, to: "/books"
  end
end

web/controllers/genre_controller.ex
defmodule Librarian.GenreController do
  use Librarian.Web, :controller

  def index(conn, _params) do
    genres = Repo.all(Librarian.Genre)
    render conn, "index.html", genres: genres
  end

  def show(conn, _params) do
    genre = Repo.preload(Repo.get(Librarian.Genre, _params["id"]), :books)
    books = genre.books
    render conn, "show.html", genre: genre, books: books
  end

  def new(conn, _params) do
    genre = Librarian.Genre.changeset(%Librarian.Genre{}, %{})
    render conn, "new.html", genre: genre
  end

  def create(conn, _params) do
    genre = Librarian.Genre.changeset(%Librarian.Genre{}, _params["genre"])
    case Repo.insert(genre)  do
      {:ok, genre} ->
        redirect conn, to: "/genres"
      {:error, genre} ->
        render(conn, "new.html", genre: genre)
    end
  end

  def edit(conn, _params) do
    genre = Repo.get(Librarian.Genre, _params["id"])
    changeset = Librarian.Genre.changeset(genre)
    render conn, "edit.html", genre: genre, changeset: changeset
  end

  def update(conn, _params) do
    genre = Repo.get(Librarian.Genre, _params["id"])
    changeset = Librarian.Genre.changeset(genre, _params["genre"])
    case Repo.insert(changeset)  do
      {:ok, genre} ->
        redirect conn, to: "/genres"
      {:error, chageset} ->
        render(conn, "edit.html", genre: genre)
    end
  end

  def delete(conn, _params) do
    genre = Repo.get(Librarian.Genre, _params["id"])
    Repo.delete_all(from(b in Librarian.Book, where: b.genre_id == ^genre.id))
    Repo.delete(genre)
    redirect conn, to: "/genres"
  end
end

web/controllers/page_controller.ex
defmodule Librarian.PageController do
  use Librarian.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/book_view.ex
defmodule Librarian.BookView do
  use Librarian.Web, :view
end

web/views/error_view.ex
defmodule Librarian.ErrorView do
  use Librarian.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/genre_view.ex
defmodule Librarian.GenreView do
  use Librarian.Web, :view
end

web/views/layout_view.ex
defmodule Librarian.LayoutView do
  use Librarian.Web, :view
end

web/views/page_view.ex
defmodule Librarian.PageView do
  use Librarian.Web, :view
end

web/templates/book/edit.html.eex
<h1>蔵書の編集</h1>
<%= form_for @changeset, book_path(@conn, :update, @book), fn f -> %>
<p>
  タイトル
  <%= text_input f, :title, placeholder: "タイトル", class: "form-control" %>
</p>
<p>
  ISBN
  <%= text_input f, :isbn, placeholder: "ISBN", class: "form-control" %>
</p>
<p>
  蔵書の場所
  <%= text_input f, :store_loc, placeholder: "タイトル", class: "form-control" %>
</p>
<p>
  <%= select f, :genre_id, @genre %>
</p>
<p>
  <%= submit "更新" %>
</p>
<% end %>

web/templates/book/index.html.eex
<table class="table">
<%= for book <- @books do %>
  <tr>
    <td><a href="<%= book_path(@conn, :show, book.id) %>"><%= book.title %></td>
  </tr>
<% end %>
</table>

web/templates/book/new.html.eex
<h1>蔵書の新規登録</h1>
<%= form_for @book, book_path(@conn, :create), fn f -> %>
<p>
  タイトル
  <%= text_input f, :title, placeholder: "タイトル", class: "form-control" %>
</p>
<p>
  ISBN
  <%= text_input f, :isbn, placeholder: "ISBN", class: "form-control" %>
</p>
<p>
  蔵書の場所
  <%= text_input f, :store_loc, placeholder: "タイトル", class: "form-control" %>
</p>
<p>
  <%= select f, :genre_id, @genre %>
</p>
<p>
  <%= submit "登録" %>
</p>
<% end %>

web/templates/book/show.html.eex
<h1 class="h1"><%= @book.title %></h1>
<table class="table">
  <tr>
    <td>ジャンル</td>
    <td>ISBN</td>
    <td>収納場所</td>
  </tr>
  <tr>
    <td><%= @book.genre.name %></td>
    <td><%= @book.isbn %></td>
    <td><%= @book.store_loc %></td>
  </tr>
</table>

web/templates/genre/edit.html.eex
<h1>ジャンルの編集</h1>
<%= form_for @changeset, genre_path(@conn, :update, @genre), fn f -> %>
<p>
  <%= text_input f, :name, placeholder: "ジャンル名", class: "form-control" %>
</p>
<p>
  <%= submit "更新" %>
</p>
<% end %>

web/templates/genre/index.html.eex
<table class="table">
<%= for genre <- @genres do %>
  <tr>
    <td><a href="<%= genre_path(@conn, :show, genre.id) %>"><%= genre.name %></td>
  </tr>
<% end %>
</table>

web/templates/genre/new.html.eex
<h1>ジャンルの作成</h1>
<%= form_for @genre, genre_path(@conn, :create), fn f -> %>
<p>
  <%= text_input f, :name, placeholder: "ジャンル名", class: "form-control" %>
</p>
<p>
  <%= submit "作成" %>
</p>
<% end %>

web/templates/genre/show.html.eex
<h1 class="h1"><%= @genre.name %></h1>
<table class="table">
<%= for book <- @books do %>
  <td><%= book.title %></td>
<% end %>
</table>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Librarian!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>